version: "3.8"

services:
  app:
    image: nullstone/laravel:local
    volumes:
      - .:/app
      - vendor:/app/vendor
    environment:
      - NULLSTONE_ENV=local
      - APP_KEY=${APP_KEY}
      - MYSQL_URL=mysql://acme:acme@db:3306/acme
      - CACHE_DRIVER=redis
      - REDIS_URL=tcp://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: acme
      MYSQL_DATABASE: acme
      MYSQL_USER: acme
      MYSQL_PASSWORD: acme

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

volumes:
  vendor: {}
