version: "3.8"

services:
  app:
    image: nullstone/laravel:local
    volumes:
      - .:/app
      - vendor:/app/vendor
    ports:
      - "9000:9000"
    environment:
      - NULLSTONE_ENV=local
      - APP_KEY=${APP_KEY}
      - POSTGRES_URL=postgres://acme:acme@db:5432/acme
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=acme
      - POSTGRES_PASSWORD=acme
      - POSTGRES_DB=acme

volumes:
  vendor: {}
