version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - app-public:/app/public
      - nginx-confd:/etc/nginx/conf.d
      - nginx-templates:/etc/nginx/templates:ro
    ports:
      - "3000:80"
    environment:
      - WEBAPP_ADDR=app:9000
    depends_on:
      - app

  app:
    build: .
    command: php-fpm8
    volumes:
      - vendor:/app/vendor
      - .:/app
      - app-public:/app/public
      - nginx-confd:/etc/nginx/conf.d
      - nginx-templates:/etc/nginx/templates
    environment:
      - INSTALL_PACKAGES_ON_BOOT=true
      - NULLSTONE_ENV=local
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DATABASE_URL=postgres://acme:acme@db:5432/acme
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=acme
      - POSTGRES_PASSWORD=acme
      - POSTGRES_DB=acme

volumes:
  vendor:
  app-public:
  nginx-confd:
  nginx-templates:
