version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - app-public:/app/public
      - nginx-confd:/etc/nginx/conf.d
      - nginx-templates:/etc/nginx/templates:ro
    ports:
      - "3000:80"
    environment:
      - WEBAPP_ADDR=app:9000
    depends_on:
      - app

  app:
    build: .
    entrypoint: /docker-entrypoint.d/local.sh
    command: php-fpm8
    volumes:
      - vendor:/app/vendor
      - .:/app
      - app-public:/app/public
      - nginx-confd:/etc/nginx/conf.d
      - nginx-templates:/etc/nginx/templates
    environment:
      - APP_ENV=local
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=true
      - DATABASE_URL=mysql://acme:acme@db:3306/acme
    depends_on:
      - db

  db:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: acme
      MYSQL_DATABASE: acme
      MYSQL_USER: acme
      MYSQL_PASSWORD: acme

volumes:
  vendor:
  app-public:
  nginx-confd:
  nginx-templates:
