version: "3.8"

services:
  app:
    image: nullstone/laravel:local
    volumes:
      - .:/app
      - vendor:/app/vendor
    ports:
      - "9000:9000"
    environment:
      - NULLSTONE_ENV=local
      - APP_KEY=${APP_KEY}
      - MYSQL_URL=mysql://acme:acme@db:3306/acme
    depends_on:
      - db

  db:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: acme
      MYSQL_DATABASE: acme
      MYSQL_USER: acme
      MYSQL_PASSWORD: acme

volumes:
  vendor: {}
